# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
